### ISSUE TITLE
Breaking on packages that use `TSFoster/elm-sha1`

### ISSUE THREAD

**Issue by bengolds** [mdgriffith/elm-optimize-level-2#26]
If you try to use functions from [`TSFoster/elm-sha1`](https://package.elm-lang.org/packages/TSFoster/elm-sha1/latest/SHA1), `elm-optimize-level-2` will crash with a semi-cryptic error.

It appears that the[ regex inside ](https://github.com/mdgriffith/elm-optimize-level-2/blob/43659895d7cdfd0c8a3580bf21532128e840d813/src/transforms/inlineWrappedFunctions.ts#L399)of `inlineWrappedFunctions` is getting a false-positive on the `A1` in `$TSFoster$elm_sha1$SHA1$loophelp`.

Making the regex a bit more specific should fix the issue.

**Comment by twop** [comment]
Thank you so much for reporting and digging in, I will try to take a look asap!

**Comment by mdgriffith** [comment]
Published as 0.1.4 🎉

**Comment by bengolds** [comment]
🚀 ✨ Fantastic! Thanks for the fix.
